# Generated by Django 4.0.2 on 2022-02-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_points', models.FileField(blank=True, null=True, upload_to='csv_points')),
                ('plot_with_points', models.ImageField(blank=True, null=True, upload_to='plots')),
            ],
        ),
    ]
